changelog:
  categories:
    - title: 🎉 新功能
      labels:
        - enhancement
        - feature
    - title: 📝 文档更新
      labels:
        - documentation
    - title: 🔧 修复
      labels:
        - bug
